version: '3'
services:
  db:
    container_name: super-doraemon-mysql
    platform: linux/x86_64
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: nodejs_super-doraemon
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
